request: "HEAD /headers HTTP/1.1\r\nHost: headers.url.com\r\nX_Underscore: yes\r\nFolded: first\r\n second\r\nCookie: a=b; c=d\r\n\r\n"
reply: "HTTP/1.1 304 Not Modified\r\nETag: \"abc\"\r\nX-Upstream: value\twith-tab\r\n\r\n"
